---
- block:  # Become block
    - name: Update ssh server
      ansible.builtin.apt:
        name: openssh-server
        state: latest
        update_cache: true
        cache_valid_time: 3600
      notify: Restart sshd

    - name: Config - Disable root login
      ansible.builtin.lineinfile:
        path: "{{ sshd_config_file }}"
        regexp: '^#?\s*PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify: Restart sshd

    - name: Config - Disable password authentication
      ansible.builtin.lineinfile:
        path: "{{ sshd_config_file }}"
        regexp: '^#?\s*PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
      notify: Restart sshd

    - name: Config - Allow only users in ssh group
      block:
        - getent:
            database: group

        - ansible.builtin.lineinfile:
            path: "{{ sshd_config_file }}"
            regexp: '^#?\s*AllowGroups'
            line: "AllowGroups ssh"
            state: present
          when: "'ssh' in ansible_facts.getent_group"
          notify: Restart sshd

  become: true
