---
- name: Become
  become: true
  block:
    - name: Update safe packages
      ansible.builtin.apt:
        autoclean: true
        update_cache: true
        upgrade: safe
        autoremove: true
