---
- block:
    - name: Ensure sudo group has sudo privileges
      ansible.builtin.lineinfile:
        path: "{{ sudoers_file_path }}"
        regexp: '^#?\s*%sudo'
        line: "%sudo ALL=(ALL:ALL) ALL"
        state: present
        validate: "{{ visudo_exec_path }} -cf %s"
        
  become: true
