---
- block:
    - name: Install hdparm
      ansible.builtin.apt:
        name: hdparm
        state: latest
        update_cache: true
        cache_valid_time: 3600

    - name: Create hdparm.conf file
      ansible.builtin.template:
        src: hdparm.conf.j2
        dest: "{{ hdparm_conf_file_path }}"
        owner: root
        group: root
        mode: 0644

  become: true
