---
- block:
    - name: Install hdparm
      ansible.builtin.apt:
        name: hdparm
        state: latest
        update_cache: true
        cache_valid_time: 3600

    - name: Create hdparm.conf file
      ansible.builtin.template:
        src: hdparm.conf.j2
        dest: /etc/hdparm.conf

  become: true
