---
- name: Remove zfs snapshots
  hosts: production
  tasks:
    - name: Remove snapshots
      community.general.zfs:
        name: "{{ item }}@before-ansible"
        state: absent
      with_items:
        - bpool/BOOT/debian
        - rpool/ROOT/debian
      become: true
